services:
  nats-echo:
    build:
      context: nats-echo
      dockerfile: Dockerfile
    ports:
      - "${NATS_ECHO_PORT}:${NATS_ECHO_PORT}"
    env_file:
      - .env
    networks:
      - nats-network
    volumes:
      - /dev/tty1:/dev/ttyhost
    privileged: true

  speakers:
    build:
      context: speakers
      dockerfile: Dockerfile
    ports:
      - "${SPEAKERS_PORT}:${SPEAKERS_PORT}"
    env_file:
      - .env
    networks:
      - nats-network
    volumes:
      - /dev/snd:/dev/snd
    privileged: true

  web-client:
    build:
      context: web-client
      dockerfile: Dockerfile
    ports:
      - "${WEB_CLIENT_PORT}:${WEB_CLIENT_PORT}"
    env_file:
      - .env
    networks:
      - nats-network

  nats-server:
    image: nats:latest
    ports:
      - "${NATS_CLIENT_PORT}:${NATS_CLIENT_PORT}" # NATS client port
      - "${NATS_MONITORING_PORT}:${NATS_MONITORING_PORT}" # NATS monitoring port
      - "${NATS_WEBSOCKET_PORT}:${NATS_WEBSOCKET_PORT}" # WebSocket port
    env_file:
      - .env
    volumes:
      - ./nats-server/nats.conf:/nats.conf
    command: -c /nats.conf
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge
