# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AddSong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AddSong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAddSong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AddSong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AddSong
    def Song(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Song import Song
            obj = Song()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AddSongStart(builder):
    builder.StartObject(1)

def Start(builder):
    AddSongStart(builder)

def AddSongAddSong(builder, song):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(song), 0)

def AddSong(builder, song):
    AddSongAddSong(builder, song)

def AddSongEnd(builder):
    return builder.EndObject()

def End(builder):
    return AddSongEnd(builder)
