# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DurationChanged(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DurationChanged()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDurationChanged(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DurationChanged
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DurationChanged
    def Duration(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def DurationChangedStart(builder):
    builder.StartObject(1)

def Start(builder):
    DurationChangedStart(builder)

def DurationChangedAddDuration(builder, duration):
    builder.PrependFloat32Slot(0, duration, 0.0)

def AddDuration(builder, duration):
    DurationChangedAddDuration(builder, duration)

def DurationChangedEnd(builder):
    return builder.EndObject()

def End(builder):
    return DurationChangedEnd(builder)
