# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FileEnded(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FileEnded()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFileEnded(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FileEnded
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def FileEndedStart(builder):
    builder.StartObject(0)

def Start(builder):
    FileEndedStart(builder)

def FileEndedEnd(builder):
    return builder.EndObject()

def End(builder):
    return FileEndedEnd(builder)
