# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class MessageContent(object):
    NONE = 0
    Print = 1
    Echo = 2
    SpeakerCommand = 3
    SpeakerQuery = 4
    SpeakerEvent = 5
    SpeakerListQuery = 6
    SpeakerListEvent = 7
    PlaylistCommand = 8
    PlaylistQuery = 9
    PlaylistEvent = 10
    Error = 11
