# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MusicVolumeChanged(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MusicVolumeChanged()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMusicVolumeChanged(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MusicVolumeChanged
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MusicVolumeChanged
    def Volume(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def MusicVolumeChangedStart(builder):
    builder.StartObject(1)

def Start(builder):
    MusicVolumeChangedStart(builder)

def MusicVolumeChangedAddVolume(builder, volume):
    builder.PrependFloat32Slot(0, volume, 0.0)

def AddVolume(builder, volume):
    MusicVolumeChangedAddVolume(builder, volume)

def MusicVolumeChangedEnd(builder):
    return builder.EndObject()

def End(builder):
    return MusicVolumeChangedEnd(builder)
