# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PauseChanged(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PauseChanged()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPauseChanged(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PauseChanged
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PauseChanged
    def Paused(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PauseChangedStart(builder):
    builder.StartObject(1)

def Start(builder):
    PauseChangedStart(builder)

def PauseChangedAddPaused(builder, paused):
    builder.PrependBoolSlot(0, paused, 0)

def AddPaused(builder, paused):
    PauseChangedAddPaused(builder, paused)

def PauseChangedEnd(builder):
    return builder.EndObject()

def End(builder):
    return PauseChangedEnd(builder)
