# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayStopped(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayStopped()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayStopped(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayStopped
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PlayStoppedStart(builder):
    builder.StartObject(0)

def Start(builder):
    PlayStoppedStart(builder)

def PlayStoppedEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayStoppedEnd(builder)
