# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlaylistStateChanged(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlaylistStateChanged()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlaylistStateChanged(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlaylistStateChanged
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlaylistStateChanged
    def Songs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Song import Song
            obj = Song()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlaylistStateChanged
    def SongsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PlaylistStateChanged
    def SongsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PlaylistStateChangedStart(builder):
    builder.StartObject(1)

def Start(builder):
    PlaylistStateChangedStart(builder)

def PlaylistStateChangedAddSongs(builder, songs):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(songs), 0)

def AddSongs(builder, songs):
    PlaylistStateChangedAddSongs(builder, songs)

def PlaylistStateChangedStartSongsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSongsVector(builder, numElems: int) -> int:
    return PlaylistStateChangedStartSongsVector(builder, numElems)

def PlaylistStateChangedEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlaylistStateChangedEnd(builder)
