# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayYoutube(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayYoutube()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayYoutube(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayYoutube
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayYoutube
    def Url(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PlayYoutubeStart(builder):
    builder.StartObject(1)

def Start(builder):
    PlayYoutubeStart(builder)

def PlayYoutubeAddUrl(builder, url):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(url), 0)

def AddUrl(builder, url):
    PlayYoutubeAddUrl(builder, url)

def PlayYoutubeEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayYoutubeEnd(builder)
