# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class PlaylistCommandContent(object):
    NONE = 0
    AddSong = 1
    ReplaceSong = 2
    RemoveSong = 3
    InsertSong = 4
