# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlaylistQuery(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlaylistQuery()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlaylistQuery(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlaylistQuery
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlaylistQuery
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PlaylistQuery
    def QueryType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # PlaylistQuery
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def PlaylistQueryStart(builder):
    builder.StartObject(3)

def Start(builder):
    PlaylistQueryStart(builder)

def PlaylistQueryAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    PlaylistQueryAddDeviceId(builder, deviceId)

def PlaylistQueryAddQueryType(builder, queryType):
    builder.PrependUint8Slot(1, queryType, 0)

def AddQueryType(builder, queryType):
    PlaylistQueryAddQueryType(builder, queryType)

def PlaylistQueryAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    PlaylistQueryAddQuery(builder, query)

def PlaylistQueryEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlaylistQueryEnd(builder)
