# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Print(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Print()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPrint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Print
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Print
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def PrintStart(builder):
    builder.StartObject(1)

def Start(builder):
    PrintStart(builder)

def PrintAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    PrintAddMessage(builder, message)

def PrintEnd(builder):
    return builder.EndObject()

def End(builder):
    return PrintEnd(builder)
