# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QuerySeek(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QuerySeek()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQuerySeek(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QuerySeek
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def QuerySeekStart(builder):
    builder.StartObject(0)

def Start(builder):
    QuerySeekStart(builder)

def QuerySeekEnd(builder):
    return builder.EndObject()

def End(builder):
    return QuerySeekEnd(builder)
