# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QueryPlay(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QueryPlay()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQueryPlay(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QueryPlay
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def QueryPlayStart(builder):
    builder.StartObject(0)

def Start(builder):
    QueryPlayStart(builder)

def QueryPlayEnd(builder):
    return builder.EndObject()

def End(builder):
    return QueryPlayEnd(builder)
