# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class QueryPlaylistState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = QueryPlaylistState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsQueryPlaylistState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # QueryPlaylistState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def QueryPlaylistStateStart(builder):
    builder.StartObject(0)

def Start(builder):
    QueryPlaylistStateStart(builder)

def QueryPlaylistStateEnd(builder):
    return builder.EndObject()

def End(builder):
    return QueryPlaylistStateEnd(builder)
