# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReplaceSong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplaceSong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReplaceSong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReplaceSong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReplaceSong
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ReplaceSong
    def Song(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from Song import Song
            obj = Song()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ReplaceSongStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReplaceSongStart(builder)

def ReplaceSongAddIndex(builder, index):
    builder.PrependInt32Slot(0, index, 0)

def AddIndex(builder, index):
    ReplaceSongAddIndex(builder, index)

def ReplaceSongAddSong(builder, song):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(song), 0)

def AddSong(builder, song):
    ReplaceSongAddSong(builder, song)

def ReplaceSongEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReplaceSongEnd(builder)
