# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Seek(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Seek()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSeek(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Seek
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Seek
    def Seek(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def SeekStart(builder):
    builder.StartObject(1)

def Start(builder):
    SeekStart(builder)

def SeekAddSeek(builder, seek):
    builder.PrependFloat32Slot(0, seek, 0.0)

def AddSeek(builder, seek):
    SeekAddSeek(builder, seek)

def SeekEnd(builder):
    return builder.EndObject()

def End(builder):
    return SeekEnd(builder)
