# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class SpeakerQueryContent(object):
    NONE = 0
    QueryMusicVolume = 1
    QueryPause = 2
    QueryPlay = 3
    QuerySeek = 4
    QueryDuration = 5
