# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpeakerQuery(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpeakerQuery()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpeakerQuery(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SpeakerQuery
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpeakerQuery
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpeakerQuery
    def QueryType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SpeakerQuery
    def Query(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SpeakerQueryStart(builder):
    builder.StartObject(3)

def Start(builder):
    SpeakerQueryStart(builder)

def SpeakerQueryAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    SpeakerQueryAddDeviceId(builder, deviceId)

def SpeakerQueryAddQueryType(builder, queryType):
    builder.PrependUint8Slot(1, queryType, 0)

def AddQueryType(builder, queryType):
    SpeakerQueryAddQueryType(builder, queryType)

def SpeakerQueryAddQuery(builder, query):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(query), 0)

def AddQuery(builder, query):
    SpeakerQueryAddQuery(builder, query)

def SpeakerQueryEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpeakerQueryEnd(builder)
