# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class SpeakerEventContent(object):
    NONE = 0
    MusicVolumeChanged = 1
    PlayStarted = 2
    PlayStopped = 3
    SeekChanged = 4
    DurationChanged = 5
    FileEnded = 6
    PauseChanged = 7
