# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

class SpeakerCommandContent(object):
    NONE = 0
    SetMusicVolume = 1
    TogglePause = 2
    Play = 3
    Stop = 4
    Seek = 5
