# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SpeakerCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SpeakerCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSpeakerCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SpeakerCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SpeakerCommand
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # SpeakerCommand
    def CommandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SpeakerCommand
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SpeakerCommandStart(builder):
    builder.StartObject(3)

def Start(builder):
    SpeakerCommandStart(builder)

def SpeakerCommandAddDeviceId(builder, deviceId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)

def AddDeviceId(builder, deviceId):
    SpeakerCommandAddDeviceId(builder, deviceId)

def SpeakerCommandAddCommandType(builder, commandType):
    builder.PrependUint8Slot(1, commandType, 0)

def AddCommandType(builder, commandType):
    SpeakerCommandAddCommandType(builder, commandType)

def SpeakerCommandAddCommand(builder, command):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)

def AddCommand(builder, command):
    SpeakerCommandAddCommand(builder, command)

def SpeakerCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return SpeakerCommandEnd(builder)
